serviceMonitor:
  enabled: true
  selfMonitor:
    enabled: true
  targets:
    - name: "vaultwarden-external"
      url: https://79.76.33.72
      hostname: vaultwarden.lysakermoen.com
    - name: "vaultwarden-internal"
      url: https://vaultwarden.k8s.lysakermoen.com
    - name: "vaultwarden-external-local"
      url: "https://vaultwarden.lysakermoen.com"
    - name: "arch-mirror-external"
      url: https://79.76.33.72
      hostname: arch.lysakermoen.com
    - name: "arch-mirror-internal"
      url: https://arch.k8s.lysakermoen.com
    - name: "arch-mirror-external-local"
      url: https://arch.lysakermoen.com
    - name: "nginx-external"
      url: https://79.76.33.72
      hostname: nginx.lysakermoen.com
    - name: "nginx-internal"
      url: https://nginx.k8s.lysakermoen.com
    - name: "nginx-external-local"
      url: https://nginx.lysakermoen.com
    - name: "syncthing-internal"
      url: https://syncthing.k8s.lysakermoen.com
      hostname: syncthing.k8s.lysakermoen.com