apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: archlinux-internal
  namespace: mirror
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-internal
spec:
  ingressClassName: internal
  tls:
    - hosts: [ "archlinux.k8s.lysakermoen.com" ]
      secretName: archlinux-internal-tls
  rules:
    - host: archlinux.k8s.lysakermoen.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mirror
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: archlinux-public
  namespace: mirror
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-public
spec:
  ingressClassName: public
  tls:
    - hosts: [ "archlinux.lysakermoen.com" ]
      secretName: archlinux-public-tls
  rules:
    - host: archlinux.lysakermoen.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mirror
                port:
                  number: 80