apiVersion: v1
kind: Service
metadata:
  name: mirror
  namespace: mirror
  labels: { app: mirror }
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector: { app: mirror }
  ports:
    - name: http
      port: 80
      targetPort: http
