apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-from-harbor
  namespace: nginx-custom-image
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-from-harbor
  template:
    metadata:
      labels:
        app: nginx-from-harbor
    spec:
      imagePullSecrets:
         - name: harbor-pull
      containers:
        - name: nginx
          image: harbor.k8s.lysakermoen.com/library/nginx:v0.1.1@sha256:4160c57fba9a89c4c4f78085497fa89e65aab80300302aabae62239c1b92856f
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: http
          resources:
            requests: { cpu: "50m", memory: "64Mi" }
            limits:   { cpu: "250m", memory: "256Mi" }