
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-internal
  namespace: nginx-custom-image
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-internal
spec:
  ingressClassName: internal
  tls:
    - hosts: [ "nginx-custom.k8s.lysakermoen.com" ]
      secretName: nginx-internal-tls
  rules:
    - host: nginx-custom.k8s.lysakermoen.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-from-harbor
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-public
  namespace: nginx-custom-image
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-public
spec:
  ingressClassName: public
  tls:
    - hosts: [ "nginx-custom.lysakermoen.com" ]
      secretName: nginx-public-tls
  rules:
    - host: nginx-custom.lysakermoen.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-from-harbor
                port:
                  number: 80