apiVersion: v1
kind: Service
metadata:
  name: nginx-from-harbor
  namespace: nginx-custom-image
  labels: { app: nginx-from-harbor }
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector: { app: nginx-from-harbor }
  ports:
    - name: http
      port: 80
      targetPort: http