apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden
  namespace: vaultwarden
  labels: { app: vaultwarden }
spec:
  replicas: 1
  selector:
    matchLabels: { app: vaultwarden }
  strategy:
    type: RollingUpdate
    rollingUpdate: { maxUnavailable: 0, maxSurge: 1 }
  template:
    metadata:
      labels: { app: vaultwarden }
    spec:
      containers:
        - name: vaultwarden
          image: vaultwarden/server@sha256:1d43c6754a030861f960fd4dab47e1b33fc19f05bd5f8f597ab7236465a6f14b
          env:
            - name: DOMAIN
              value: "https://vaultwarden.lysakermoen.com"
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
            - name: data
              mountPath: /data
          readinessProbe:
            httpGet: { path: "/alive", port: http }
            initialDelaySeconds: 2
            periodSeconds: 5
          resources:
            requests: { cpu: "100m", memory: "128Mi" }
            limits:   { cpu: "500m", memory: "1Gi" }
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: vaultwarden-pvc
      securityContext:
        runAsNonRoot: false 
