expose:
  type: ingress
  tls:
    enabled: true
    certSource: secret
    secret:
      secretName: harbor-tls
  ingress:
    className: internal
    hosts:
      core: harbor-tmp.k8s.lysakermoen.com
      notary: notary.k8s.lysakermoen.com
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-internal
    tls:
      - hosts:
          - harbor-tmp.k8s.lysakermoen.com
        secretName: harbor-tls
      #- hosts:
      #    - notary.k8s.lysakermoen.com
      #  secretName: notary-tls

externalURL: https://harbor-tmp.k8s.lysakermoen.com

notary:
  enabled: false
chartmuseum:
  enabled: true
trivy:
  enabled: true

persistence:
  enabled: true
  resourcePolicy: "keep"
  persistentVolumeClaim:
    registry:
      storageClass: rook-ceph-block-hdd
      size: 10Gi
    chartmuseum:
      storageClass: rook-ceph-block-ssd
      size: 5Gi
    jobservice:
      storageClass: rook-ceph-block-ssd
      size: 5Gi
    database:
      storageClass: rook-ceph-block-ssd
      size: 10Gi
    redis:
      storageClass: rook-ceph-block-ssd
      size: 2Gi
    trivy:
      storageClass: rook-ceph-block-ssd
      size: 10Gi

metrics:
  enabled: true