apiVersion: ENC[AES256_GCM,data:VR8=,iv:OD2SWCUhi7peLnWqeHRxcpGz4S6v/v7HKbLhXpoo/1M=,tag:ZBGbvVzOLasbKIbgm7tThA==,type:str]
kind: ENC[AES256_GCM,data:PEPQJMLm,iv:POMfEc0DT268igv1CmEklzapJTTog9hMK2QHyQPeImo=,tag:vdB4Lk5X77AGFhD17g7dRA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:j7E5okxcAAhg05GbrZRxJRth,iv:j4uxQis74HgVeesTxyx3Nvi9dxNZgnP52QRYJOs42/4=,tag:W49U2tkkj2hEi3RU4KmLdg==,type:str]
    namespace: ENC[AES256_GCM,data:cuiNHthq83uv4g==,iv:9+MWNSRnsSmFnSiWfwkZipPXQXuyFD8FrsOCUprRuUw=,tag:JU5Fo8tEqz5FOSNfyl4IEQ==,type:str]
type: ENC[AES256_GCM,data:dxHwu3Cd,iv:M0su1iunMJiKaXaeYLRda98Zq0gbepDl3cZYhjgm6OM=,tag:6ZZjXXxcsgoXiLMYQK5K8A==,type:str]
stringData:
    DISCORD_WEBHOOK: ENC[AES256_GCM,data:SJu5eMjAWnq/jITDTEdoPMNj5N/kQUymtTxMJ/WY7JlUNG+lTq/NQrMWrOdrhkL86L397oTK8UNGyl2zFlNvS32hSxMgt5Hsw4WOxW3BmBBeUDb64ECKVXWGwfS8ydv0tPHd2cdmZGfHc+sl5/w6fe6KrO94ZK/XsQ==,iv:57/Gv4nCQSRjqjQ/3yUBewcRu1z5TcWYVyXF4FiEHYM=,tag:ovFsRJn+88BUQSfW42Yatg==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICvT+ITNOzjlDdcTk9kdYLrGYd0EJw6kMr6Ynw9165wR sander@nixos-laptop
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IE9hRWxSdyBJOUpm
            ejA3Q3lra0pBSWNZSWpVSjJBMjBmYjFOU3ZhTFdTUmpMYmQ5c1dFCjQ1ZHdNcGV1
            eE5HbWU3SnJDRHVNL3hVTUVQblVKOGNkcWoxdldMU2F1bjAKLS0tIDFsV0F0amxu
            NTBWajZIZGxldnpySFVEWHYya0FkbWNGbW52eXJYMkJuUTgKAngLsqrLvEpkmQvT
            7QGo/ibngdt3nE7qswvVXqE8RdfI+Nwt0uxFc7yyNv78pTMVkSNkfY/6w2oBoM62
            aUQioA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGhMesnzIJ89Ic38a3cOFUtiqE/No4FRFkhX+IqIIO3S sander@nixos
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHZpQ3Y3dyBaaWdy
            a2JuT3A0Q0hsR0h3NUJQejlUcHpPOXdJbm9BdnloNjNYc05tT0FnCitkZ2JvMi92
            RnFlemo3TmNzdzFGZUVKd3NxdVRvdnVsVkZobkpHblhMdUEKLS0tIDB2OU9Ia0ZZ
            dytDZmtmdzZPVjRlTWl2SlVpV2pTVXpOVUpybm5kVTlCTFUKHgczjHBsDodXIm8X
            GB24iWt3N/cGidtsiOzms5D+K/LYhkEYPXuJw+F0aXmUQa5NemKQse/0s44aHThp
            mhr7fw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFHe3wCRa3OBsJZJsnXgDDbWaIB18hq0RKUzU1eGqoco slysa@asus-proart
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IElVbEhTQSBSSHJk
            RWVQcWoraGxDL3l2cGNwWEk3bFBYbEtuVCs3cG56VnBzd2t2ZW1nCjV0ZDMrbngv
            SGN4M1hzOFUxSlQrZlk5OGwxaTUzUUR0SmRDc0lBL3hFTE0KLS0tIGlwOGdJMXFT
            L05jK0ZndW0vL0swbS9BSGZJN09QaGQ5MUdpVklLdTdZbGcKen2h7nHFAz/5NlNL
            6LMORbYLLYtnB/HcVjcLtru2LT6rdlounm29avP3Zh47BnLgW7/gVh1LQ0wTs2Ja
            PBxedA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIB3+7P7YnvA6ghkemNkLLwoFZL/oTBLUOIz8K5SyQwS6 slysa@desktop
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IFBtM1RTUSBxdlYv
            MitZR3JLN1JlcFM5cHhjdytGZjBCU0M2ZmJUK0J5eG5TWWdjeFhZCnNkSCtHY05n
            Z3R2VkZXeHR5bkN1Z3BKSDNaMkVEY1lKamx2ZW9aVytkUWsKLS0tIDJkaWNIRkRW
            SW53akN0dlBpNHo3NWlyYktrU3Z5TlRpNVhOTUNLdHZ5ZWMKnJqWBlKKmvKwgBIy
            2OTdWhPMvuuKIGdTk/QEmnBAj4d0kqEc9xeIpmFzMmDld4gav72CRSK3RF/FFXN0
            W/zmqw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age185wsded9nj5vsw58saezfj8wekkftmpsrhv9cd05ep3k5vap8ckqc9epjn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMZ3YyQVB1ZXd1N0dGUVBU
            RDljeUZ5RkZIT0dnb0N6RGNBdFJlMTRGdTJNCnV4aTVTNVh1UTRNWkZ1RmhGZW55
            YnY1NitxRDZzR1FrMjZQa2FJaVIrR0kKLS0tIFlnSkRKc2FqQ0I2ekhRYlU4RDY1
            aHQ4QVo0NWoxejNyYXZzL1U5WjR0djQKgzOcGu0ME1pMuVhGsR5DASxHf9RhQW8+
            +l9sWnSpAftcn0XRSJFkfrJJCbZ9VjY8V1Xyzlj2mR5gbreW92F/Iw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIL031Q1Dd6yu310sGwE4++BdJIad4gApbWlsPpMI8Mcx sander@linux
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IG1XOCttdyBUb29s
            b3l1TkI2VW1lRUp4RmNheGViQldRUGptTWxSL2ZRZU5KeXJyR0VVCmljQzcrSUY1
            cFBqc2d4TFRFZWtJczZLbUdKL2NBYm1PZ0hOQXBEbHQzU2MKLS0tIHRFWVJmcVlM
            Y3RWUWk1cjdmS0ZiOUxnYmgvY2F2eEhzUVBOc0hhNy9UQUEKaR1I7irrJeAUXkTo
            Emw82423HJSxSrg+BV9zXWobcQAz9oyYlO/lmrL4ZBhts2WQrLwfsnoMqeo6Q6m9
            KYKQgw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-20T15:12:53Z"
    mac: ENC[AES256_GCM,data:rZQinnLCgqDMn9YUmsgI9gB470s286ZoJty0Kn6eoJ4kRabjQJ1KmaM3zSvDrucHqz44flvy5zDho2tw/0gI2vN5iKoQU1mN3cfDAW9P0JIAwg/60QBXDc/v4kBKSfg5oTq5J0Lw5f+EzAGRO++H/NvMoaywGlncmGstOWDKAu0=,iv:6vOFfgxRhx7KYkHufBsBMQit2MLE6TkyQV2kHAxMFlU=,tag:BLcxjDocHms4lx49xtpZrw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
