apiVersion: ENC[AES256_GCM,data:VR8=,iv:OD2SWCUhi7peLnWqeHRxcpGz4S6v/v7HKbLhXpoo/1M=,tag:ZBGbvVzOLasbKIbgm7tThA==,type:str]
kind: ENC[AES256_GCM,data:PEPQJMLm,iv:POMfEc0DT268igv1CmEklzapJTTog9hMK2QHyQPeImo=,tag:vdB4Lk5X77AGFhD17g7dRA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:j7E5okxcAAhg05GbrZRxJRth,iv:j4uxQis74HgVeesTxyx3Nvi9dxNZgnP52QRYJOs42/4=,tag:W49U2tkkj2hEi3RU4KmLdg==,type:str]
    namespace: ENC[AES256_GCM,data:cuiNHthq83uv4g==,iv:9+MWNSRnsSmFnSiWfwkZipPXQXuyFD8FrsOCUprRuUw=,tag:JU5Fo8tEqz5FOSNfyl4IEQ==,type:str]
type: ENC[AES256_GCM,data:dxHwu3Cd,iv:M0su1iunMJiKaXaeYLRda98Zq0gbepDl3cZYhjgm6OM=,tag:6ZZjXXxcsgoXiLMYQK5K8A==,type:str]
stringData:
    DISCORD_WEBHOOK: ENC[AES256_GCM,data:SJu5eMjAWnq/jITDTEdoPMNj5N/kQUymtTxMJ/WY7JlUNG+lTq/NQrMWrOdrhkL86L397oTK8UNGyl2zFlNvS32hSxMgt5Hsw4WOxW3BmBBeUDb64ECKVXWGwfS8ydv0tPHd2cdmZGfHc+sl5/w6fe6KrO94ZK/XsQ==,iv:57/Gv4nCQSRjqjQ/3yUBewcRu1z5TcWYVyXF4FiEHYM=,tag:ovFsRJn+88BUQSfW42Yatg==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICvT+ITNOzjlDdcTk9kdYLrGYd0EJw6kMr6Ynw9165wR sander@nixos-laptop
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IE9hRWxSdyBJSFBR
            cWppSmhJVU1iZWgzZzcvMHZuQ0JEV04ycElURDdZK3Y0RkRXc0JrClVNTGFtVjR0
            aFBYUnAyVmZOVVhEeEFXdjlMQ0tmY0xPYlBVTUFjMXFUdDQKLS0tIHlnSE56Um9B
            Ni9DVE5XU05zNmR1YmNMSnBZQ0VqR3NFRldxcnoxdW02RzQKn/+cSOTR5Q1Kno0w
            ay2KGHnc6ACXCUoi4u3lFsUJHpPqJfpfwTMf+Qlc0GL6IwYejH8NupR+iBzYUwJJ
            ME7CKQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGhMesnzIJ89Ic38a3cOFUtiqE/No4FRFkhX+IqIIO3S sander@nixos
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHZpQ3Y3dyBNcVht
            Z2pwcXVjTk1WYWtXdVlHRmtFRStxa1hRUWZTWFBTRnJHUXpNa0gwClRCRHJKVmwr
            eTc1aXc3a3IvVTdsdFlTVzBCUmlCN2xoQlZjMjFNNVVqVUEKLS0tIHhZWTI3VGRz
            eXVVblppNG1nbFFXVThKVFNjc2lzVHZMTU1mS1BuTWdVdk0KOJzXwQAVBAoUsmr7
            2JuaNUVGh4NAsgPFNazXMG45hkDkPQiBSa0/xGke63M/6XwAtpvXYM+Olq3EWomK
            cramFw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFHe3wCRa3OBsJZJsnXgDDbWaIB18hq0RKUzU1eGqoco slysa@asus-proart
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IElVbEhTQSBVTGZs
            MmFJREZvaTdvdGcvOExJRWtNK2RoT0lhRjA1TnNZVUJWT055Nlg0CmJkQUYxYTky
            UlVJRDcxVDVVNFVES21jUEl2bTlPbzcrTFNpelNLNGRiV2MKLS0tICs5UnlhNDQy
            YWhoMkRpY2VCSkk0cUJmQ3FwN1h0OVNFTklZVWJnQVBPbVkKxybTZNEb95CDvBSF
            eKTK0mylB1ICEtkCtTq1MjoY0VCVZdNFbcAGM5Jf2PhDuo7NVjduut2K3z45eqUV
            SW8WxQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIB3+7P7YnvA6ghkemNkLLwoFZL/oTBLUOIz8K5SyQwS6 slysa@desktop
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IFBtM1RTUSAyejRM
            eFcxWVRVTGlGeWZIK2pTVjNEazkvZlVDZU5IL3ZEa3JXekdCclZjCjV0QzdFeGtx
            NTJxZXVuRG1DcDZTa1RscDVKYnJocXVENDhjTTBIOWJTOUEKLS0tIG5BTjJRRStx
            UmVPdkE3NUpTekNieG4rSzdiUXJsVnNLOEdrOTBvcEZEUEkKUwyjJ2Ih1q/PCTTF
            +f8GuFOI35DoKl34X+xjyVLlgMW6uhaaCtB98mIH2GPbtJcaPMvQiKaQ+m1qCMhj
            x8n44w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age185wsded9nj5vsw58saezfj8wekkftmpsrhv9cd05ep3k5vap8ckqc9epjn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFOHZRNFIydkNxemp5V3B5
            TlU4Sm1OSTRMejA3SU11ZzU5OEN0VHNaaFE0CnJNbHY3bUlXM2ZXU3Z1eU9nU09E
            WWdiblczNnoxU09CbXRmU2c0TEZpdncKLS0tIE5ZR1Y0N0kyYWpKbjMzY21JRzI3
            eW5oVzhPWEVYUE1yS0g5THNJTWwrZVkKEN0ERv7Xvc4Wrfka0d8hs3mPJGegVMAI
            l1tiNbARjc/rKYVAFmJMRQGVe9ARm+Qz8ABQ72xaQacHBStfeSrXrA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-20T15:12:53Z"
    mac: ENC[AES256_GCM,data:rZQinnLCgqDMn9YUmsgI9gB470s286ZoJty0Kn6eoJ4kRabjQJ1KmaM3zSvDrucHqz44flvy5zDho2tw/0gI2vN5iKoQU1mN3cfDAW9P0JIAwg/60QBXDc/v4kBKSfg5oTq5J0Lw5f+EzAGRO++H/NvMoaywGlncmGstOWDKAu0=,iv:6vOFfgxRhx7KYkHufBsBMQit2MLE6TkyQV2kHAxMFlU=,tag:BLcxjDocHms4lx49xtpZrw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
