apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tobbeos-public
  namespace: tobbeos
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-public
spec:
  ingressClassName: public
  tls:
    - hosts: [ "tobbeos.lysakermoen.com" ]
      secretName: tobbeos-public-tls
  rules:
    - host: tobbeos.lysakermoen.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tobbeos
                port:
                  number: 80