deploymentMode: SingleBinary
loki:
  auth_enabled: false
  storage:
    type: filesystem

SimpleScalable:


singleBinary:
  replicas: 1
  persistence:
    enabled: true
    storageClass: rook-ceph-block-ssd
    size: 20Gi
retention_period: 168h # 7 days